### ISSUE TITLE
Can I use this to bypass input restriction? [QUESTION]

### ISSUE THREAD

**Issue by playingoDEERUX** [atipls/SwitchInputClient#1]
Fortnite would usually kick you from the game when trying to use a different input device,
can I use this for advantage purposes  to use my PC/Keyboard while battling against others who use normal Switch input? (cuz I assume this still makes the game think that normal switch input is being used which is basically my question)

If its too 'flaky' then I will try to see myself if I can do something about it in code but I am interested into the idea of this project.

Also I don't want to get banned...

thx for answering my question if u do, I hope you will stay within context of this question (and not bully me or smth)...

**Comment by atipls** [comment]
Not sure what platform you are talking about, as Fortnite on the Switch
does not support keyboard input at all.

This is probably against the Fortnite TOS, testing was done in creative

The plan is to support configurable keybinds for most games but this is a
very early project
